import { z } from 'zod';

export const TradeInputSchema = z.object({
  date: z.string().transform((val) => new Date(val)),
  entryTime: z.string(), // Can be ISO string or time string
  exitTime: z.string().nullable().optional(),
  session: z.string().optional().default('NY Open'),
  challengePhase: z.string().optional().default('Phase 1'),
  asset: z.string().min(1, 'Asset is required'),
  direction: z.enum(['BUY', 'SELL']),
  setupTypes: z.array(z.string()).optional().default([]),
  entryPrice: z.number().positive('Entry price must be positive'),
  stopLoss: z.number().positive('Stop loss must be positive'),
  tp1: z.number().positive('TP1 must be positive'),
  tp2: z.number().positive('TP2 must be positive'),
  tp3: z.number().positive().nullable().optional(),
  exitPrice: z.number().positive().nullable().optional(),
  exitReason: z.string().nullable().optional(),
  checklistScore: z.number().min(0).max(13).optional().default(0),
  checklistItems: z.array(z.boolean()).optional().default([]),
  preReasoning: z.string().optional().default(''),
  postNotes: z.string().nullable().optional(),
  mistakes: z.string().nullable().optional(),
  partialClose: z.boolean().optional().default(false),
  breakevenMoved: z.boolean().optional().default(false),
  screenshots: z.array(z.string()).optional().default([]),
  emotionBefore: z.array(z.string()).optional().default([]),
  emotionAfter: z.array(z.string()).nullable().optional(),
  disciplineRating: z.number().min(0).max(5).nullable().optional(),
  wouldRetake: z.string().nullable().optional(),
  revengeTradeFlag: z.boolean().optional().default(false),
  fomoFlag: z.boolean().optional().default(false),
  followedRules: z.boolean().optional().default(true),
  brokenRule: z.string().nullable().optional(),
  pressureToTrade: z.boolean().optional().default(false),
});
